# Generated by Django 4.0.4 on 2022-06-05 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemetala',
            name='name',
            field=models.CharField(choices=[('Группы:1.1;1.2;11.1 СТБ ISO 15608 (Ст3,20,09Г2С,16ГС,17Г1С)', 'Группы:1.1;1.2;11.1 СТБ ISO 15608 (Ст3,20,09Г2С,16ГС,17Г1С)'), ('Группа:6.2 CТБ ISO 15608 (12Х1МФ,15Х1М1Ф)', 'Группа:6.2 CТБ ISO 15608 (12Х1МФ,15Х1М1Ф)'), ('Группа:8.1 CТБ ISO 15608 (12Х18Н9,12Х18Н9Т,12Х18Н12Т,08Н18Н10Т)', 'Группа:8.1 CТБ ISO 15608 (12Х18Н9,12Х18Н9Т,12Х18Н12Т,08Н18Н10Т)')], help_text='Выберите основной металл А', max_length=200),
        ),
        migrations.AlterField(
            model_name='basemetalb',
            name='name',
            field=models.CharField(choices=[('Группы:1.1;1.2;11.1 СТБ ISO 15608 (Ст3,20,09Г2С,16ГС,17Г1С)', 'Группы:1.1;1.2;11.1 СТБ ISO 15608 (Ст3,20,09Г2С,16ГС,17Г1С)'), ('Группа:6.2 CТБ ISO 15608 (12Х1МФ,15Х1М1Ф)', 'Группа:6.2 CТБ ISO 15608 (12Х1МФ,15Х1М1Ф)'), ('Группа:8.1 CТБ ISO 15608 (12Х18Н9,12Х18Н9Т,12Х18Н12Т,08Н18Н10Т)', 'Группа:8.1 CТБ ISO 15608 (12Х18Н9,12Х18Н9Т,12Х18Н12Т,08Н18Н10Т)')], help_text='Выберите основной металл B', max_length=200),
        ),
    ]
