# Generated by Django 4.0.4 on 2022-06-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_basemetala_name_alter_basemetalb_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amperage',
            name='amperage',
            field=models.CharField(help_text='Укажите силу тока, А', max_length=10),
        ),
    ]
