# Generated by Django 4.0.4 on 2022-06-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_amperage_amperage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgebluntingsize',
            name='edgesize',
            field=models.CharField(help_text='Укажите величину притупления кромок, мм', max_length=10),
        ),
        migrations.AlterField(
            model_name='excesspenetration',
            name='excess',
            field=models.CharField(help_text='Укажите превышение проплава на высоту, мм', max_length=5),
        ),
    ]
