# Generated by Django 4.0.4 on 2022-06-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_edgebluntingsize_edgesize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fillerdiameter',
            name='diameter',
            field=models.CharField(help_text='Укажите диаметр присадочного материала, мм', max_length=5),
        ),
        migrations.AlterField(
            model_name='gapsize',
            name='gapsize',
            field=models.CharField(help_text='Укажите величину зазора в собранном стыке, мм', max_length=10),
        ),
        migrations.AlterField(
            model_name='heatingtemp',
            name='temp',
            field=models.CharField(help_text='Укажите температуру подогрева', max_length=5),
        ),
        migrations.AlterField(
            model_name='interrollertemp',
            name='temp',
            field=models.CharField(help_text='Укажите межваликовую температуру', max_length=10),
        ),
        migrations.AlterField(
            model_name='partsize',
            name='size',
            field=models.CharField(help_text='Укажите типоразмер деталей, мм', max_length=20),
        ),
        migrations.AlterField(
            model_name='seamreinforceheight',
            name='height',
            field=models.CharField(help_text='Укажите высоту усиления шва, мм', max_length=5),
        ),
        migrations.AlterField(
            model_name='seamwidth',
            name='seamwidth',
            field=models.CharField(help_text='Укажите ширину шва, мм', max_length=5),
        ),
        migrations.AlterField(
            model_name='sectionangle',
            name='angle',
            field=models.CharField(help_text='Укажите угол разделки кромок', max_length=20),
        ),
        migrations.AlterField(
            model_name='speed',
            name='speed',
            field=models.CharField(help_text='Укажите скорость, м/мин', max_length=10),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temp',
            field=models.CharField(help_text='Укажите температуру', max_length=10),
        ),
        migrations.AlterField(
            model_name='voltage',
            name='voltage',
            field=models.CharField(help_text='Укажите напряжение, В', max_length=10),
        ),
    ]
